server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: tus-server
  web:
    resources:
      static-locations: file:./static/,/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/public/
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: test
    password: test
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
tus-server:
  file-directory: /tmp/tus-server
  max-size: 524288000
  tus-checksum-algorithms: md5,sha1
  context-path: /tus/upload/
  duration: 1
logging:
  level:
#    priv.dino.tus.server: DEBUG
    org.springframework.r2dbc: DEBUG